version: '3.7'
services:

  # MySQL8
  db:
    image: mysql:8
    container_name: mysqldb
    profiles: ["db"]
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=propiedadesalpes
      - MYSQL_ROOT_PASSWORD=adminadmin
    networks:
      - internal

  pulsar:
    image: apachepulsar/pulsar:3.2.0
    container_name: pulsar
    profiles: ["pulsar"]
    restart: on-failure
    ports:
      - "6650:6650"
      - "8080:8080"
    command: ["bin/pulsar", "standalone"]
    networks:
      - internal

networks:
  internal: