[project]
name = "propiedadesalpes"
version = "1.0.0"
authors = [
  { name="the Code Team"},
]
description = "Proyecto propiedades de los alpes"
readme = "README.md"
requires-python = ">=3.10"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = [
  ".", "src",
]